#!/bin/bash

# set variables we need
PLUGIN_NAME="jjgrainger-plugin"
PLUGIN_VERSION=1.0

echo "zipping ${PLUGIN_NAME} v${PLUGIN_VERSION}"

# zip everything in the current directory
zip -r ${PLUGIN_NAME}.zip . -x *.git* *.DS_Store* *.travis.yml* '*script/*'

mkdir _build
mv ${PLUGIN_NAME}.zip _build/${PLUGIN_NAME}.zip

ls _build
