#!/bin/bash

# set variables we need
PLUGIN_NAME="jjgrainger-plugin"
PLUGIN_VERSION=1.0

echo "zipping ${PLUGIN_NAME} v${PLUGIN_VERSION}"

# zip everything in the current directory
mkdir build
zip -r build/${PLUGIN_NAME}.zip .
